Add package scripts & automatic publish release (#54)
* Add package script

Signed-off-by: masteryyh <yyh991013@163.com>

* Let workflow publish release automatically when pushing new tag

Signed-off-by: masteryyh <yyh991013@163.com>

---------

Signed-off-by: masteryyh <yyh991013@163.com>

diff --git a/.github/workflows/build-image.yaml b/.github/workflows/build-image.yaml
--- a/.github/workflows/build-image.yaml
+++ b/.github/workflows/build-image.yaml
@@ -13,9 +13,19 @@ jobs:
     runs-on: ubuntu-24.04
     permissions:
       packages: read
+      contents: write
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
+      - name: Check if corresponding release note presents
+        if: startsWith(github.ref, 'refs/tags/v')
+        run: |
+          FILE="docs/notes/release-${{ github.ref_name }}.md"
+          if [ ! -f "$FILE" ]; then
+            echo "Error: Release note does not exist."
+            exit 1
+          fi
 
       - name: Initialize Golang environment
         uses: actions/setup-go@v5
@@ -80,3 +90,12 @@ jobs:
           platforms: linux/amd64,linux/arm64,linux/riscv64
           file: Dockerfile.alpine
           tags: masteryyh/micro-ddns:alpine3.21,masteryyh/micro-ddns:${{ github.ref_name }}-alpine3.21,masteryyh/micro-ddns:alpine
+
+      - name: Publish a release using new tag
+        if: startsWith(github.ref, 'refs/tags/v')
+        run: |
+          gh release create ${{ github.ref_name }} \
+            -F docs/notes/release-${{ github.ref_name }}.md
+            output/*.tar.gz*
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
